### ISSUE TITLE
PDFView not rendering {% if ... %} and {% for ... %} Django template blocks

### ISSUE THREAD

**Issue by esther-ish** [WhyNotHugo/django-renderpdf#10]
Hello, I am using Django 2.2 and Django Rest Framework 3.11.

I am trying to use `{% if foo %}` and `{% for bar in bars %}` in my HTML file. However, I quickly noticed it does not work, that is, HTML codes that fall under the `if` and `for` block do not get rendered as PDF.

Is there a possible way to get this done? The documentation does not cover any examples using logic. Thank you

**Comment by WhyNotHugo** [comment]
Was the issue in hour code? I assumed you've managed to get through it, right?
