### ISSUE TITLE
Problemas para imprimir codigo qr con django-renderpdf

### ISSUE THREAD

**Issue by edgar-anello** [WhyNotHugo/django-renderpdf#12]
El proyecto tiene instalado:

pip show django-qr-code
Name: django-qr-code
Version: 2.1.0
Summary: An application that provides tools for displaying QR codes on your Django site.
Home-page: https://github.com/dprog-philippe-docourt/django-qr-code

pip show django-renderpdf
Name: django-renderpdf
Version: 3.0.1
Summary: A django app to render django templates as PDF files.
Home-page: https://django-renderpdf.readthedocs.io/

El QR en form html se ve correctamente como muestra la consola:

[20/Apr/2021 15:20:55] "GET /qr-code/images/serve-qr-code-image/?text=TUVDQVJEOk46TWljaGFlbCBKb3JkYW47VEVMOis1NDk1MjItMTIzNCAxMjM0O0VNQUlMOm1pY2hhZWwuam9yZGFuQGdtYWlsLmNvbTtCREFZOjE5NjMwMjE3O0FEUjo0MDggLSBMb3RlIDMgLSAoMTg5MCkgQ2l0eSBCZWxsIC0gTGEgUGxhdGEsIEJ1ZW5vcyBBaXJlcztVUkw6aHR0cFw6Ly8xMjcuMC4wLjFcOjgwMDAvc29jaW9zLzIvO09SRzpDbHViIEF0bGV0aWNvIFYuIFNhbiBDYXJsb3M7Ow%3D%3D&cache_enabled=True&size=4&image_format=png&error_correction=l&token=4.4..png.l.YquLczBgr4dSXTP4pcrd%3AH70jL4IsI2SY_unitlx9HK0AyOjHqZyz10PTP5L6NEI HTTP/1.1" 200 726

El error se produce en:
class PrintCredencialView(LoginRequiredMixin, PDFView):

El html genera el dpf con todos los campos exepto el codgio QR 
<div class="qr">
      <img src="{% qr_url_for_contact contact_detail=qr options=my_options %}">
</div>
lanza el siguiente error:
ERROR 2021-04-21 12:06:20,340 images 12656 139828574455552 Failed to load image at "/qr-code/images/serve-qr-code-image/?text=TUVDQVJEOk46RWRnYXIgQW5lbGxvO1RFTDorNTQ5MjIxNjAwNDY2NjtFTUFJTDpzeXNhQGFsZHlsLmNvbS5hcjtCREFZOjE5NTYwOTI0O0FEUjptb250ZXZpZGVvIHkgOTQgLSBMb3MgVGFsYXMgLSAoZXggcnRhIDE1KSAtICgxOTIzKSBCZXJpc3NvIC0gQmVyaXNzbywgQnVlbm9zIEFpcmVzO1VSTDpodHRwXDovLzEyNy4wLjAuMVw6ODAwMC9zb2Npb3MvMS87T1JHOkNsdWIgQXRsZXRpY28gVi4gU2FuIENhcmxvczs7&cache_enabled=True&size=4&image_format=png&error_correction=l&token=4.4..png.l.qXSQFltQVws9n9RZVnGO%3ADLgUfTTEXcRsFijmmQIQtng9cOhRu481uwKAdUhcQhU" (InvalidRelativeUrl: No view matched `/qr-code/images/serve-qr-code-image/?text=TUVDQVJEOk46RWRnYXIgQW5lbGxvO1RFTDorNTQ5MjIxNjAwNDY2NjtFTUFJTDpzeXNhQGFsZHlsLmNvbS5hcjtCREFZOjE5NTYwOTI0O0FEUjptb250ZXZpZGVvIHkgOTQgLSBMb3MgVGFsYXMgLSAoZXggcnRhIDE1KSAtICgxOTIzKSBCZXJpc3NvIC0gQmVyaXNzbywgQnVlbm9zIEFpcmVzO1VSTDpodHRwXDovLzEyNy4wLjAuMVw6ODAwMC9zb2Npb3MvMS87T1JHOkNsdWIgQXRsZXRpY28gVi4gU2FuIENhcmxvczs7&cache_enabled=True&size=4&image_format=png&error_correction=l&token=4.4..png.l.qXSQFltQVws9n9RZVnGO%3ADLgUfTTEXcRsFijmmQIQtng9cOhRu481uwKAdUhcQhU`.)

**Comment by WhyNotHugo** [comment]
El drama parece ser en que tu path para la imágen es un path relativo (e.g.:  `/qr-code/image...`) en vez de absoluto (e.g.: `https://www.example.com/qr-code/image...`).

Cuando renderpdf trata de cargar la imágen, no tiene como cargar esa ubicación. Tenés dos opciones:

### Opción 1 

Agregar tu BASE_URL (o como le llames) en el template. Esto implicaría que el renderer hace un request HTTP para obtener la imágen, funciona y es lo más fácil, pero tiene complejidad innecesaria.

```htmldjango
{{ BASE_URL }}/qr-code/image...
```

Debería renderear a :


```htmldjango
https://www.example.com/qr-code/image...
```

### Opción 2

Podés para la imágen como un string base64. Hay un ejemplo de eso mismo acá:

https://github.com/WhyNotHugo/django-afip/blob/main/django_afip/templates/receipts/code_6.html#L114-L116

La variable `qrcode` sale de acá:

https://github.com/WhyNotHugo/django-afip/blob/main/django_afip/pdf.py#L56-L63

Por si no estás familiarizado con imágenes en base64 inline así, acá hay un ejemplo de una imágen real (un punto rojo) y como lo renderea el navegador: https://jsfiddle.net/hpP45/

Si usás el template principalmente para PDFs, te recomiendo este approach que es más confiable y eficiente.

**Comment by edgar-anello** [comment]
Gracias Hugo, muy clara tu respuesta. 
Gracias por compartir tu conocimiento, aprovecho para felicitarte django-renderpdf y django-afip son dos herramientas espectaculares.
Saludos 
Edgar.-
***@***.***
