### ISSUE TITLE
Does this support Chart.js rendering? 

### ISSUE THREAD

**Issue by JaredOzzy** [WhyNotHugo/django-renderpdf#6]
Hi, Was just wondering if this supports the javascript execution of javascript rendering before generating the pdf.

at the moment weasyprint and wkhtmltopdf are problematic, might try to get this working if it doers support javascript rendering.

**Comment by JaredOzzy** [comment]
I tried it out now and unfortunately I SEE this package doesn't render the JS :(

**Comment by WhyNotHugo** [comment]
Hi. Nope, this uses `weasyprint` under the hood (it's mostly a weasyprint-django integration).

**Comment by WhyNotHugo** [comment]
If you need to render PDF based on JS, you might be better off using a headless browser, though that's another level of complexity.
