### ISSUE TITLE
[Question] Collaborating with django-weasyprint

### ISSUE THREAD

**Issue by DmytroLitvinov** [WhyNotHugo/django-renderpdf#70]
Hi there :) 

Just checked libraries for WeasyPrint in Django world and found this one and [django-weasyprint](https://github.com/fdemmer/django-weasyprint)

And I found interesting issue - https://github.com/fdemmer/django-weasyprint/issues/69
As for recent activity in that repo I understand that there will be not merge of libraries, right?

**Comment by WhyNotHugo** [comment]
Nobody's actively working on that, no.

I haven't had much chance do work on this library, and everything that I need is working fine, so there hasn't been any reason to prioritise doing so.

**Comment by DmytroLitvinov** [comment]
Got it. Thanks for the answer 🙂
I think we can close that issue-question?
