### ISSUE TITLE
select_template: TypeError: select_template() takes an iterable of template names but got a string

### ISSUE THREAD

**Issue by jayvdb** [WhyNotHugo/django-renderpdf#8]
On Django 2.2

```py
  File "/usr/local/lib/python3.6/site-packages/django_renderpdf/helpers.py", line 110, in render_pdf
    html = select_template(template).render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader.py", line 34, in select_template
    'template by name.' % template_name_list
TypeError: select_template() takes an iterable of template names but got a string: 'foo.html'. Use get_template() if you want to load a single template by name.
```

**Comment by WhyNotHugo** [comment]
Can you provide a short snippet of your code that triggers this error?

Thanks!

**Comment by jayvdb** [comment]
`render_pdf('foo.html', data, context=context)`

**Comment by WhyNotHugo** [comment]
This function takes a list of templates, and will use the first one found:

```python
render_pdf(['foo.html'], data, context=context)
```

**Comment by WhyNotHugo** [comment]
Leaving the ticket open as a reminder to document this  better

**Comment by jayvdb** [comment]
This is a regression - it was working fine in my production system before upgrading.  Fair enough, this was a major upgrade, but it should be noted as a breaking change.

**Comment by WhyNotHugo** [comment]
Agreed. Sorry about the breakage. This was an undocumented function. I'll document it as-is and leave the current API stable (this one aligns better with Django's APIs).

**Comment by WhyNotHugo** [comment]
#11 restores backwards compatibility. I'll add this in v3.0.1 soon.
