### ISSUE TITLE
Errors while installing django-renderpdf

### ISSUE THREAD

**Issue by csandreas1** [WhyNotHugo/django-renderpdf#9]
I am using django 2.2.7 and python 3.8.0

After running pip install django-renderpdf I am getting errors

pip install django-renderpdf                   
Collecting django-renderpdf
  Using cached django_renderpdf-3.0.0-py3-none-any.whl (7.4 kB)
Collecting weasyprint
  Using cached WeasyPrint-52.1-py3-none-any.whl (304 kB)
Requirement already satisfied: django>=2.2 in c:\django_venv\rest\venv\lib\site-packages (from django-renderpdf) (2.2.7)
Collecting tinycss2>=1.0.0
  Using cached tinycss2-1.1.0-py3-none-any.whl (21 kB)
Collecting CairoSVG>=2.4.0
  Using cached CairoSVG-2.5.0-py3-none-any.whl (45 kB)
Collecting cairocffi>=0.9.0
  Using cached cairocffi-1.2.0.tar.gz (70 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\django_venv\rest\venv\scripts\python.exe' -c

**Comment by WhyNotHugo** [comment]
Is that the entire output?

There's no error message here, so I've nothing to go on.
